ARG version
FROM almalinux:${version:-9}
ENV course="devops" \
    duration="120hrs"
ARG trainer="siva"
ENV TRAINER=
RUN echo "hi, course is:${course}, duration is:${duration}, trainer is:${siva}, version is:${version}"
CMD ["sleep", "1000"]    